### ISSUE TITLE
Story: GUI for Team Detail page

### ISSUE THREAD

**Issue by michelleli94** [diamondinrough/feature_01#19]
GUI should display the information that is particular to the team:
1. Team name
2. Number of team member, number of new team tasks, number of total team tasks. (Question: what is the criteria for "new"?)
3. Team leader (clickable, lead to leader's profile page)
4. Team description
5. Team members (each team member is clickable, lead to member's profile page)
6. Tasks (a "more tasks" button that leads to the page for all tasks for the team)
7. Display name for one or more tasks that fit into the screen
8. At the bottom, provide a "Request to Join Team" button that takes user to "Join Team Request" page, which will be covered by a different issue

![oneteam](https://cloud.githubusercontent.com/assets/11450439/13565815/5342f164-e407-11e5-8c06-ac28db146e82.PNG)

**Comment by bryanly200** [comment]
This is the structure of what using my getTeambyID(teamID) will return

{
'num_total_tasks': 6,
 'num_team_members': 1,
 'team_tasks': ['Get tofu', 'Get chips', 'Get mushrooms', 'Get shrimp', 'Get shrimp', 'Get soda'],
 'team_leader': '17-Tyler-Green',
 'team_name': 'Team 1',
 'num_new_tasks': 5,
 'team_description': 'Team 1 description',
 'team_members': ['22-Bob-Campbell']
}

**Comment by michelleli94** [comment]
As of 04/08, the team detail does not work on master branch, when clicking on one of the hot teams on landing page or the team on all teams page. The error message on console showed that it can not find the http://localhost:80/appuser/team/<team id> in urls.py
