### ISSUE TITLE
Story: GUI for Task Detail page

### ISSUE THREAD

**Issue by michelleli94** [diamondinrough/feature_01#21]
The GUI should implement the followings:
1. Task title
2. Task team, Task creation date
3. Task description
4. Task due/expiration date
5. Task members/participants
6. At the bottom, provide a "Request to Join Task" button that takes user to a "Join Task Request" page 

![onetask](https://cloud.githubusercontent.com/assets/11450439/13566111/c494d246-e408-11e5-9b54-1dce5059f150.PNG)

**Comment by bryanly200** [comment]
Calling getTaskbyID(taskID) will return something similar to the structure below.
{
    'task_description': ' Replace the existing Tsarist government with a Socialist government controlled by the Bolshevik party',
    'creation_date': '2016-03-21T14:20:17Z', 
    'task_name': ' Overthrow the Tsarist Government', 
    'members': ['BolsheSICK', 'Tsarist Jesus'], 
    'task_leader': ' Vlad Lenin'
}

**Comment by bryanly200** [comment]
{
'creation_date': '2016-03-27T04:31:57Z', 
'members': ['MexicanStereotype', 'SouthernStereotype'], 
'team_name': 'Marketing', 
'task_name': 'task1', 
'task_description': ' task1 description', 
'team_leader': 'MexicanStereotype', 
'signup_due_date': '2017-05-01'
} 

this is an update version from above with the other information you need for the page

**Comment by michelleli94** [comment]
Two more changes for this issue:
1. Handle the exception when task_leader is not available
2. Return a empty dictionary when the specified task ID is not found

**Comment by michelleli94** [comment]
This has been completed in milestone #2
