### ISSUE TITLE
Story: Personal Profile page: GUI

### ISSUE THREAD

**Issue by michelleli94** [diamondinrough/feature_01#23]
GUI should provide the following information for selected personnel:
1. Name
2. Team, position
3. City, occupation
4. Participation duration
5. Teams (display one, provide a button to display more teams)
6. Tasks (display the number of tasks, provide a button to display all tasks)
7. Manage team members (only available for leaders?) that takes user to a team member management page
8. Tasks status (provide a button to see status detail)
9. Education histories 
10. On upper right hand corner, provide a "Settings" button that takes login user to update his/her profile info, which will be covered by a different story.

**Interface for login user's own profile:**
![image](https://cloud.githubusercontent.com/assets/11450439/14068157/41d33c58-f42f-11e5-89e0-63b49d55d321.png)

![image](https://cloud.githubusercontent.com/assets/11450439/14068161/5e020f8a-f42f-11e5-8721-477c603187aa.png)

**Interface for administrator user's profile:**
![image](https://cloud.githubusercontent.com/assets/11450439/14068186/0cd15016-f430-11e5-8511-0edaae3fde67.png)
![image](https://cloud.githubusercontent.com/assets/11450439/14068188/303a4ad0-f430-11e5-958c-a8fb668896cc.png)

**Comment by mliu9333** [comment]
The array should come out to:
'first_name', 'last_name', 'team_position', 'city', 'occupation', 'college_name', 'major', 'college_start_date', 'college_end_date', 'team_name', 'num_total_tasks', 'new_tasks', 'completed_tasks'

Feel free to message me if there's any issue :)

**Comment by OrangeHeap** [comment]
需要添加company position以及正在做的任务数量

**Comment by bryanly200** [comment]
resolved
