### ISSUE TITLE
Story: Personal Profile Settings: GUI

### ISSUE THREAD

**Issue by michelleli94** [diamondinrough/feature_01#25]
GUI to allow user edit his/her profile settings:
1. Icon
2. Name
3. City
4. Employment status
5. Work experience
6. Education history

**Main information interface:**
![image](https://cloud.githubusercontent.com/assets/11450439/14068196/adffab04-f430-11e5-9944-d6c9830ab889.png)

**Self-introduction interface:**
![image](https://cloud.githubusercontent.com/assets/11450439/14068198/d571ce38-f430-11e5-9a41-a1fc85fc3d87.png)

**Comment by bryanly200** [comment]
resolved
