### ISSUE TITLE
Story: Personal Profile Settings page: Backend

### ISSUE THREAD

**Issue by michelleli94** [diamondinrough/feature_01#26]
Backend to support the followings, refer to corresponding GUI page for all information that backend needs to support based on the GUI screenshot:
Provide existing information
1. Icon
2. Name
3. City
4. Employment status
5. Work experience
6. Education history
Support/Save update of above information

**Comment by cihrsliu** [comment]
getPersonnelProfileSettingsData returns dictionary with all fields in DirPersonnel (check schema), 'name' which is the first name and the last name together, 'recent_education' and 'recent_employment' which are dictionaries with fields from the most recent education and employment (check schema)

**Comment by bryanly200** [comment]
resolved
