### ISSUE TITLE
Story: Move database settings

### ISSUE THREAD

**Issue by cihrsliu** [diamondinrough/feature_01#32]
Move database settings outside of Django's settings.py and load database config from /opt/dir/etc/my.cnf

**Comment by cihrsliu** [comment]
Implemented to Chris branch
changed settings.py so that Django loads database settings from /opt/dir/etc/my.cnf
![mycnf](https://cloud.githubusercontent.com/assets/17556679/13931500/0394009e-ef7a-11e5-8e4b-abdf69d4e1a8.png)

**Comment by michelleli94** [comment]
This has been completed in milestone #2. Wiki doc "Test Environment" has also been updated with instructions on how to configure my.cnf
