### ISSUE TITLE
Story: Display more tasks for the particular team

### ISSUE THREAD

**Issue by michelleli94** [diamondinrough/feature_01#72]
On the Team Detail page, when there is not enough room to display all tasks fro the team, there is a "more" link that will lead to a page that display all tasks that belong to the team, clicking on one of the task here will lead to the task detail.

**Comment by michelleli94** [comment]
Send question to product manager, but haven't heard back.

To implement this, instead of a "more" link to next page, we will provide a down arrow, which will expand and all tasks for the team. A up arrow, which will retract and only display one task

**Comment by WarrenXiaGG** [comment]
This was already commited

**Comment by bryanly200** [comment]
verified
