### ISSUE TITLE
Story: Backend to support content for landing page

### ISSUE THREAD

**Issue by michelleli94** [diamondinrough/feature_01#8]
Backend to provide the followings:
1. Teams to be displayed
2. Most recent 5 tasks

**Comment by cihrsliu** [comment]
Implemented and tested successfully in screenshots
![tasks](https://cloud.githubusercontent.com/assets/17556679/13927875/e443a06a-ef69-11e5-8872-9b5b40fcd019.png)
![site](https://cloud.githubusercontent.com/assets/17556679/13927876/e44457a8-ef69-11e5-8bd0-972f4e435657.png)

**Comment by michelleli94** [comment]
This task has been completed for milestone #2
